# Generated by Django 4.0.5 on 2022-06-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_total_cost_in_rubles_after_comma'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_is_send_date', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='messages')),
            ],
        ),
    ]
