# Generated by Django 4.0.5 on 2022-06-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_botmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmessages',
            old_name='message_is_send_date',
            new_name='message_send_date',
        ),
    ]
